spring:
  timezone: Asia/Seoul
  datasource:
    url: jdbc:postgresql://localhost:5432/pet_db
    username: joowon
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create


server:
  servlet:
    session:
      timeout: 30m
